language: clojure

lein: 2.7.1

sudo: required

services:
- docker

env:
  global:
    - secure: FNsyAH7FP9c/KU9gnd2Ne9wt47esyOyJlcIUtk/4UlaMHKvjiqAqx30f8cztwB+Kbe0vqMSgxP3tYN2pyN7ILSK52X8stTUFIkZtkjWS+ii4R9uCkTz7rLjIPHs2jxEDf1h+69XecXqPjg3O2csMDIH4+g7ek9NIzxSK1etxM/o6anSLrVwzHDQlfXUR/eeh5V97jpqUDpxgCxg4x192be6vzk1aeOY9oglQ94ISJWUXGKAlPIk7jNmcLSj+b69FhDw/w/JoEM3Tlix2PGxYPHgaZUyTQ8pt/12xxMGac31XS7jJjtzb+F+QZ/fQfGuR5mDyzpAxTw1jbmGeHnBFZxzhLMhP82q1xjKnXBsaGIPq52SKjViBleRWXsCNzTYxN5+XQbu27jI52UdhkVP3yIhzSiqtmu8aTDQtUugBuUqZmCN7vti+L1Ubvy+4CLzfUmulIN++FLLLxAHYPctGDpnrjuB5HknKejF0Kd2/3iyc9HQrP1QOdUdwMDsL6BnBfCVzO8bd7H2dd7N/tPBgz9i6RE7ruC3YxrotcSPfKLCmjjgWXKap5Fk3a6JEBVnpn6CMELrDHpeIZYV5J8/Y3ykF2VoxicIswuVpnCcE7R2uY0N64/6xRReMgs+0gCEHTkd3an6b00dSydao7ALigo8vJV9LN/FnRkADUCjeno0=
    - secure: n6cxcXasiMBewhwe00BwV3AW1c337vU7oV/QNHQynMe3eqL1sbYD1E2T9Qst2YuGQxPQim1pexkpophozfsVJ0XI+xEJlAf7AB5oWGFABrBe0XZmUxAFJEB7wfb2hCgQrTllCS2vcKG1gXO1rde1h+Td6/nDu2szNUBfnZTVVsvOvyC6BxFfgzV4n1Jd6xdBuAqOdFlu/DdoWHMnnxdQz+3YvSlLqZ5tNAR8EwZl8u33C5tLrx/N8zwiUKIwmpk9GIjUBY5PShPOAy7Eumm/htYKKAN+wKcKRGm4eDKAJ956qr9y6mPpGBVxueH3T4/oHQSwYYmgVTfPoccgM+R/hTpm+c6wAUmhTQqwOZph8nWn7ScCQFDkB6YLefCu/egcCuFWAHXYQr7XfjTmofS1QUGh2ScotIWRofKUaJsBDF+J8sNlh0jXk4T/k+j3SoxbKp6JiLB+VjeahTFzN+fgYIepUMq5wnE4VeHxDZiXgfymXnKXL4qkTAwnbawwdiMZ6zEIHUq/3kbm6Fs9OUimuBkRJ3ir+NC0vakWUw7aevcvFz3BOenGuxLdDEy6bxgwcv0ftsbRn1fKscHPvvywOx7asTMbhfq+oQC8OI/9sryLKlaWL0LTDbBj9bw91bkjoBgkEzpf5vG4P5efJV2N6M3L67vETUBfPqAikgtTIj0=

script:
- docker run -e POSTGRES_PASSWORD=mysecretpassword -p 15432:5432 -d postgres
- lein cljfmt check
- sleep 3
- lein migrate
- lein test
- lein ring uberjar

deploy:
- provider: releases
  api_key:
    secure: aB4+VZBs7MxwnHlmyJstABV8g4x5/oNz+92XngSoAijt6MwbVOiDbRXHX7Hwwn0wZKko9oVIU9zIzKmL9TG4tbtUDtUoVsedkPEuTMjOoxKLTLySNZ7/BHfEJcwFxHtvdlUZweOceznFTpjSi4c+NBdU2u7Fktx+6uMon2I6lMx5jle3qPuMTZG4R5AwN3FWa8dIuNZ6s6qKaVcYz2xZf2yNwE0xM2Hrb/vYCZQpYIqYP6/fnUpKHdFbCTOTC7SMr17jRJA16ietIGmHsq/TSS5gjWF9H3DtxTPNLlS2w4GRGZV+VvDi/0HqsHCa5NMBIDgIrY0LM9sNA/yHnc/hGAHsq/FpC3mozjnt2rsF4+35ndEPC1ZoSmJsDD30RCdGp9a6g8Z1pAzg7dyvxvmUDafrKsBEGw5m3CYtDvht0r6nt5Ot7sQArdQuY4jE8S1w0va7jb2NVkG9o/QXrm9BoqlUDpKmj4+cls362FYvBuz0KyJXbfGVDU3owLmVswedyPtmtzFM0KjKIsah4nrQR0L1s45U6PT7tJIw6u0PCRG/79qY2wmq0McfVnXMl/j+dReHPHhsfX6FSxYMFPlLhF4OPUkKP55dA1i1JM6XS0veVCO4j39SsGzbHjLrRkBR/q6iw6ybntRtZ8cBOVKLTjh8zu6SkyI3mtWlDXR42Lw=
  file: target/uberjar/api-standalone.jar
  skip_cleanup: true
  on:
    tags: true

- provider: heroku
  api_key:
    secure: NqNP+62MkyTt79tEtDX+TQWM/gxUGLuBhCyOjMmAcAp3rj/U2q4zv46rMOREeQNsRs58KalrpP8yDu7Ho3NEmIlQTTxlVJeItAZAIJ8oZo2+HYNMszxsCQbX2f0yv4qiX0a2VIzazgMgRUc26AbMTtYMDCrQ/TdgRGmVfOkLI9yAfdK13zZru/3Sx4oEclxOznsJpCwH5HrCwHFeIX3hq2mG94qxRTEAk56GRPwP8HBk39/8uRNKOyuDUI5Qn44FLsMlIQcLjRYzp/vVmF8cV5zzH3qsXQBpyZDJfP1xkTyAeRsXQ9gIcgQW8R/m1HKdMty/wcoO64FgFgTvpM2PZZ63vi8QenL+yWfiGNESryw2RiXC57I66GnQGe0Evd6URr16eQPiRWaVjLmk6fZEhq6hbEb3Er6kdUsjeobDzaImtaGayok7I6v/6tS7UQZZRUjdyc3KsoOBPtAK+L+HV+EbfDIIEHc8nu2/o/DXq9mOPUalQEBaY9KEvidw4wkl/i1o8yAHP0sqP+cVfDFiC2u4bo8ziBlDBGxPjl0AQWLejUlhW6NbgnxoLA6GgJIvPR4EiupYjh4/fQkU0cU7QQWpgn6MhXOnIklXliuYRDru8KAqubHo8KI+/rCJFD4gGr/psD5Q5HDVZ+dovWOqerBd+9yxA4ZrLAp4d9AUX4g=
  app: optly-api

after_success:
- ./bin/docker/push

jdk:
- openjdk7
